# Generated by Django 3.0.8 on 2020-07-30 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maimai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This may only contain letters, digits, and @/./+/-/_ characters.', 'invalid')], verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('confirm_password', models.CharField(max_length=128, verbose_name='confirm password')),
                ('first_name', models.CharField(max_length=30, verbose_name='first Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
            ],
        ),
    ]
